import os
from app.agents.base_agent import BaseAgent
from app.tools.gemini_client import ask_llm
from app.config import settings
from app.utils.logger import get_agent_logger, log_thinking, log_acting


class CodeGenAgent(BaseAgent):
    def __init__(self, name, bus):
        super().__init__(name, bus)
        self.logger = get_agent_logger("CodeGenAgent")
    def parse_files(self, output: str):
        """
        Parse LLM output in the format:

        FILE: path/to/file.py
        ```python
        code
        ```
        """
        files = {}
        current_file = None
        buffer = []

        lines = output.splitlines()

        for line in lines:
            if line.strip().startswith("FILE:"):
                # save previous file
                if current_file:
                    files[current_file] = "\n".join(buffer).strip()
                    buffer = []

                current_file = line.replace("FILE:", "").strip()

            else:
                # skip ``` markers
                if line.strip().startswith("```"):
                    continue
                buffer.append(line)

        # save last file
        if current_file:
            files[current_file] = "\n".join(buffer).strip()

        return files

    async def think(self, message):
        log_thinking(self.logger, "CodeGenAgent")

        task = message["task"]
        context = message["context"]

        task_name = task["name"]
        description = task["description"]
        output_file = task["output_file"]

        prompt = f"""
            You are an expert Python developer.

            Task:
            {description}

            Context:
            {context}

            The main implementation file should be:
            {output_file}

            Your responsibilities:
            1. Write clean, modular, production-quality Python code.
            2. ALSO generate comprehensive pytest test cases.

            Requirements:

            ### Implementation
            - Write the full implementation.
            - Use best practices and modular structure.

            ### Tests
            - Create ALL required test files.
            - Use pytest.
            - Cover normal, edge, and failure cases.

            ### File Structure
            - Place source code appropriately.
            - Place tests inside `tests/` directory.
            - Test files must be named `test_*.py`.

            ### Imports
            - Tests must correctly import implementation.
            - Code should run without modification.

            ### Output Format (STRICT)
            Return multiple files using:

            FILE: <filepath>

            Do NOT include explanations.

            Ensure everything runs with pytest.
            """
        
        return {
            "type": "codegen",
            "task": task_name,
            "description": description,
            "prompt": prompt
        }
        

    async def act(self, plan):
        log_acting(self.logger, "CodeGenAgent")

        raw_code = ask_llm(plan["prompt"], settings.CODEGEN_MODEL)

        # parse multiple files
        files = self.parse_files(raw_code)

        if not files:
            raise ValueError("No files generated by LLM.")

        generated_paths = []

        for relative_path, content in files.items():
            full_path = os.path.join(settings.REPO_PATH, relative_path)

            os.makedirs(os.path.dirname(full_path), exist_ok=True)

            with open(full_path, "w") as f:
                f.write(content)

            generated_paths.append(full_path)
            self.logger.info(f"Generated file: {full_path}")

        return {
            "type": plan["type"],
            "task": plan["task"],
            "description": plan["description"],
            "files": generated_paths,
        }
